name: Build Android APK

on:
  workflow_dispatch: # Manuel olarak tetikleme
  push:
    branches:
      - main
    paths:
      - "ReactNativeMobileApp/**"
      - ".github/workflows/build-android.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ReactNativeMobileApp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: ReactNativeMobileApp/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Generate Android project
        run: npx expo prebuild --platform android --clean

      - name: Create network security config
        run: |
          mkdir -p android/app/src/main/res/xml
          cat > android/app/src/main/res/xml/network_security_config.xml << 'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <network-security-config>
              <!-- Allow cleartext traffic for local network -->
              <base-config cleartextTrafficPermitted="true">
                  <trust-anchors>
                      <certificates src="system" />
                  </trust-anchors>
              </base-config>
          </network-security-config>
          EOF

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: steering-wheel-app-release
          path: ReactNativeMobileApp/android/app/build/outputs/apk/release/app-release.apk

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Steering Wheel App v1.0.${{ github.run_number }}
          files: ReactNativeMobileApp/android/app/build/outputs/apk/release/app-release.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
